### ISSUE TITLE
About php5 branch

### ISSUE THREAD

**Issue by daggerhart** [codemasher/php-qrcode#11]
First off, thank you very much for this library!

I'm working with the Drupal 8 [GA Login](https://www.drupal.org/project/ga_login) module and we're hoping to use this library. We have the 2.x branch of this library working well, but had a user run into a [problem with the minimum php version](https://www.drupal.org/project/ga_login/issues/2937404) being 7.x.

Since Drupal 8 still officially supports PHP 5.6 I think it's in the GA_Login module's best interest to do the same, so I'm curious what you can tell me about the last version of this library that supported php5.6.

It looks like to me that we could use version [1.1.0 from packagist](https://packagist.org/packages/chillerlan/php-qrcode#1.1.0) and support php5.6. Does that sound right to you?

If 1.1.0 branch would work for us, do you think there is any reason why we (GA_Login module) shouldn't use it? Is it significantly behind in features we might need, or insecure in some way?

Thanks again for dropping by the ga_login issue queue and for the great library!

**Comment by codemasher** [comment]
To be honest: i'd rather advise this one person to upgrade their php version to 7+. I've declared php5 for dead a year ago already and dropped support for it - 7.0 is seeing its end already and nobody should be using php5 still. Long term support does not mean we should still be actively developing for it, but rather encourage upgrading. (but that's my only personal opinion ;)

Anyway, i've used my phpstorm superpowers and saw that it was only the combined imports and scalar type hints as well as 2 null coalesce operator, so the change took only a couple minutes - voilà: https://github.com/codemasher/php-qrcode/commit/1ba7f204e13cd2313fd68fb30baf5b32a17dc3bd

**Comment by daggerhart** [comment]
This is awesome, thank you so much for taking the time to make these changes! What do you think my next step would be to use this branch? I'm no composer expert, so I'm not sure where to go from here. Are you planning to making this part of the official 2.x branch and continuing to support php 5.6 officially? Or will this live as its own branch and become available through packagist? I've never provided a library through packagist so I don't really know how much work I'm asking of you. Please let me know if I can help in any way.

As far as encouraging upgrades, I'm with you there. I maintain a few WP related projects, and if you don't like supporting php 5.6 you should try having to support php 5.2 🙄. But ultimately I try to support whatever the platform supports because not every developer is in a position to change their hosting setup. I have a lot of empathy for devs who are stuck having to do whatever they are told to do because I've been there.

Thanks again!

**Comment by codemasher** [comment]
You're very welcome! I'm no composer/packagist expert either and i'm trying to find out how i can tag the php5 release so that it does not interfere with master. `2.0.1-php5` didn't show up on packagist and i'm a bit clueless. 

I  don't plan to merge it back into the main branch - strict type hinting in php7 is one of the things i don't want to live without anymore. I've even [started dropping anything less than 7.2](https://github.com/codemasher/php-database/commit/44df9d29fe1ca01c135769aa6e8f0c7795ab7a47) because 7.2 finally brings strong encryption and more awesome stuff - it's a delight writing php like that. 
As much as i can understand not being able to upgrade, i prefer to be up-to-date and future proof. 
There is a point where it's no longer worth the effort staying backward compatible, especially in a language that has some reputation for its security issues and when EOL is less than a year away (for both, [5.6 and 7.0](http://php.net/supported-versions.php)) so it's not only time to encourage people to upgrade, but eventually also ring the alarm bells too.

I'm glad that i'm in a position that allows me to do what i want - i've got a "normal" day job that pays my bills and programming is what i do as a hobby - i preserves the creativity, and while i'm at it i'm trying to refresh some outdated things and maybe make some people's lives easier (which also means, i'll do the things i just did for you if it's feasible).
 
cheers!

**Comment by codemasher** [comment]
update! i managed to get it under the stable relase tag 1.0.8! `"chillerlan/php-qrcode": "1.0.8"`. Please let me know if that works for you. Thanks!

**Comment by daggerhart** [comment]
Awesome! I think this is perfect and we can close this issue.

Thanks again for the help with everything!

**Comment by codemasher** [comment]
That's great! I'm going to close this issue. Feel free to add any feedback!
